### ISSUE TITLE
banning my own IP

### ISSUE THREAD

**Issue by KaMiKaZeE443** [palinkas-jo-reggelt/hMailServer-Firewall-Ban#13]
Hello.
So after setting this all up, everything seems like it works, it's banned the correct IP's and puts them in the firewall just like it should however, the script keeps banning my external IP address, the IP is not blocked in hMail itself, but the script keeps adding it to the firewall, I'm honestly not to sure why.

One more small issue is I'm getting "Cannot read property 'apply' of undefined" when loading the webUI. https://i.imgur.com/13XF1Hj.png

I have no other scripts with hMailServer.

hMailServer version - 5.6.8-B2501
Apache version - 2.4.41
Mysql version - 10.3.16.0
PHP version - 7.4.1
OS - Windows 10 (Latest update)
Latest version of hMailServer-Firewall-Ban

**Comment by palinkas-jo-reggelt** [comment]
You need to exclude your IP in eventhandlers.vbs. Is it a fixed IP?

If oClient.IPAddress = "123.231.132.31" Then Exit Sub

If not a fixed IP (like me hehe...), then 

Function WANIP
	With CreateObject("DNSLibrary.DNSResolver")
		WANIP = .IPv4A("mydomain.tld")
	End With
End Function

If oClient.IPAddress = WANIP Then Exit Sub


The  "Cannot read property 'apply' of undefined" has something to do with the google map. I was never able to fix that, so I commented out the map section on index.php. Maybe I'll look into it again, but I put several hours into fixing it already and no dice. :(

**Comment by KaMiKaZeE443** [comment]
That fixed it!
Thank you very much I was so confused haha.
Also commenting out line 56 to 61 in index.php fixes that Cannot read property 'apply' of undefined issue.

**Comment by palinkas-jo-reggelt** [comment]
I'm not sure why the map stopped working. Apparently google changed something. Too bad. It was pretty cool. I even got it to shrink on phone screens. Maybe other's have had the same issue and more info is available on the internet. I'll give it a stab when I have time.
