### ISSUE TITLE
Complex password may a problem

### ISSUE THREAD

**Issue by EmEiBee** [palinkas-jo-reggelt/hMailServer-Firewall-Ban#14]
Just a Hint:
If you have a password that have the sign $ (Dollar) in then you run at the wall and get never a connect to the DB. Can be that are also other signs that make trouble die they are reserved for PS ...
PS count that as variable due in the "GeoLite2SQL-Functions.ps1" at line 69 the connect string is build by doublequotes. 
Replacing all with singlequotes and all goes well...

There is at least one other problem (at least for me) when importing the "geocountry" table. The fields "networt_start" and "network_end" are filled with some wild hieroglyph instead of IP addresses.
But since I'm walking away from HMS anyway, I won't pursue this any further...

**Comment by palinkas-jo-reggelt** [comment]
> Just a Hint: If you have a password that have the sign $ (Dollar) in then you run at the wall and get never a connect to the DB. Can be that are also other signs that make trouble die they are reserved for PS ... PS count that as variable due in the "GeoLite2SQL-Functions.ps1" at line 69 the connect string is build by doublequotes. Replacing all with singlequotes and all goes well...

You're working with an older version. I dropped the file "GeoLite2SQL-Functions.ps1" a while ago. 

Also, it seems that you're posting in the wrong repository.

**Comment by EmEiBee** [comment]
Yep, wrong repo; my mistake...
The other... Let me think... Downloadet round about 2 Month ago, maybe cached... I have no idea...

But no matter... Just delete my wrong threads, then everything will be fine again ;)
